"""Initial schema — full Sales Operating System table set.

Converts all SQLite TEXT primary keys and foreign keys to UUID,
TEXT timestamps to TIMESTAMP WITH TIME ZONE, TEXT JSON blobs to JSONB,
and INTEGER booleans to BOOLEAN — all native Postgres types.

Revision ID: 001
Revises:
Create Date: 2026-05-05 00:00:00.000000
"""

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# ---------------------------------------------------------------------------
# Revision metadata
# ---------------------------------------------------------------------------
revision: str = "001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _uuid_pk() -> sa.Column:
    """UUID primary key column, auto-generated by the DB."""
    return sa.Column(
        "id",
        postgresql.UUID(as_uuid=True),
        primary_key=True,
        server_default=sa.text("gen_random_uuid()"),
        nullable=False,
    )


def _uuid_fk(name: str, ref_table: str, nullable: bool = True) -> sa.Column:
    return sa.Column(
        name,
        postgresql.UUID(as_uuid=True),
        sa.ForeignKey(f"{ref_table}.id", ondelete="SET NULL"),
        nullable=nullable,
    )


def _ts(name: str, nullable: bool = True, server_default_now: bool = False) -> sa.Column:
    """TIMESTAMP WITH TIME ZONE column."""
    kw: dict = {}
    if server_default_now:
        kw["server_default"] = sa.text("now()")
    return sa.Column(name, sa.TIMESTAMP(timezone=True), nullable=nullable, **kw)


# ---------------------------------------------------------------------------
# upgrade
# ---------------------------------------------------------------------------

def upgrade() -> None:
    # Enable the pgcrypto / uuid-ossp extension for gen_random_uuid().
    # gen_random_uuid() is built-in from Postgres 13+; the extension call is a
    # no-op on Postgres 15 but harmless.
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")

    # ── product_catalog ───────────────────────────────────────────────────────
    op.create_table(
        "product_catalog",
        _uuid_pk(),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("type", sa.Text(), nullable=True),
        sa.Column("category", sa.Text(), nullable=True),
        sa.Column("subcategory", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("primary_goal", sa.Text(), nullable=True),
        sa.Column("core_value", sa.Text(), nullable=True),
        sa.Column("interaction_value", sa.Integer(), nullable=False, server_default="1"),
        sa.Column("marketing_influence", sa.Integer(), nullable=False, server_default="1"),
        sa.Column("score_multiplier", sa.Numeric(precision=6, scale=4), nullable=False, server_default="0"),
        sa.Column("funnel_stage", sa.Text(), nullable=True),
        sa.Column("primary_channel", sa.Text(), nullable=True),
        sa.Column("automation_potential", sa.Text(), nullable=True),
        sa.Column("source_reference", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default="true"),
        _ts("created_at", server_default_now=True),
        _ts("updated_at", server_default_now=True),
    )
    op.create_index("ix_product_catalog_category", "product_catalog", ["category"])
    op.create_index("ix_product_catalog_funnel_stage", "product_catalog", ["funnel_stage"])
    op.create_index("ix_product_catalog_is_active", "product_catalog", ["is_active"])

    # ── bundles ───────────────────────────────────────────────────────────────
    op.create_table(
        "bundles",
        _uuid_pk(),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("value_proposition", sa.Text(), nullable=True),
        _ts("created_at", server_default_now=True),
        _ts("updated_at", server_default_now=True),
    )

    # ── bundle_items ──────────────────────────────────────────────────────────
    op.create_table(
        "bundle_items",
        _uuid_pk(),
        _uuid_fk("bundle_id", "bundles", nullable=False),
        _uuid_fk("product_id", "product_catalog", nullable=False),
        sa.Column("sequence_order", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("required", sa.Boolean(), nullable=False, server_default="true"),
    )
    op.create_index("ix_bundle_items_bundle_id", "bundle_items", ["bundle_id"])
    op.create_index("ix_bundle_items_product_id", "bundle_items", ["product_id"])

    # ── need_states ───────────────────────────────────────────────────────────
    op.create_table(
        "need_states",
        _uuid_pk(),
        sa.Column("problem_name", sa.Text(), nullable=True),
        sa.Column("detected_signal", sa.Text(), nullable=True),
        sa.Column("severity", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
    )

    # ── need_state_products ───────────────────────────────────────────────────
    op.create_table(
        "need_state_products",
        _uuid_pk(),
        _uuid_fk("need_state_id", "need_states", nullable=False),
        _uuid_fk("product_id", "product_catalog", nullable=False),
        sa.Column("priority_order", sa.Integer(), nullable=False, server_default="1"),
        sa.Column("recommendation_reason", sa.Text(), nullable=True),
    )
    op.create_index("ix_need_state_products_need_state_id", "need_state_products", ["need_state_id"])

    # ── upsell_rules ──────────────────────────────────────────────────────────
    op.create_table(
        "upsell_rules",
        _uuid_pk(),
        _uuid_fk("primary_product_id", "product_catalog"),
        sa.Column("trigger_event", sa.Text(), nullable=True),
        _uuid_fk("client_need_state_id", "need_states"),
        _uuid_fk("recommended_product_id", "product_catalog"),
        sa.Column("upsell_type", sa.Text(), nullable=True),
        sa.Column("expected_impact", sa.Text(), nullable=True),
        _uuid_fk("dependency_product_id", "product_catalog"),
    )

    # ── cross_sell_rules ──────────────────────────────────────────────────────
    op.create_table(
        "cross_sell_rules",
        _uuid_pk(),
        _uuid_fk("product_id", "product_catalog"),
        _uuid_fk("paired_product_id", "product_catalog"),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("bundle_strength", sa.Integer(), nullable=False, server_default="3"),
    )

    # ── clients ───────────────────────────────────────────────────────────────
    op.create_table(
        "clients",
        _uuid_pk(),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("segment", sa.Text(), nullable=True),
        sa.Column("status", sa.Text(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        _ts("created_at", server_default_now=True),
        _ts("updated_at", server_default_now=True),
    )
    op.create_index("ix_clients_segment", "clients", ["segment"])
    op.create_index("ix_clients_status", "clients", ["status"])

    # ── opportunities ─────────────────────────────────────────────────────────
    op.create_table(
        "opportunities",
        _uuid_pk(),
        _uuid_fk("client_id", "clients"),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("stage", sa.Text(), nullable=True),
        sa.Column("detected_need_summary", sa.Text(), nullable=True),
        sa.Column("owner_user_id", sa.Text(), nullable=True),
        _ts("created_at", server_default_now=True),
        _ts("updated_at", server_default_now=True),
    )
    op.create_index("ix_opportunities_client_id", "opportunities", ["client_id"])
    op.create_index("ix_opportunities_stage", "opportunities", ["stage"])

    # ── recommendations ───────────────────────────────────────────────────────
    op.create_table(
        "recommendations",
        _uuid_pk(),
        _uuid_fk("opportunity_id", "opportunities"),
        sa.Column("recommendation_type", sa.Text(), nullable=True),
        _uuid_fk("target_product_id", "product_catalog"),
        sa.Column("confidence_score", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column("rationale", sa.Text(), nullable=True),
        sa.Column("status", sa.Text(), nullable=True),
        _ts("created_at", server_default_now=True),
    )
    op.create_index("ix_recommendations_opportunity_id", "recommendations", ["opportunity_id"])
    op.create_index("ix_recommendations_status", "recommendations", ["status"])

    # ── agent_templates ───────────────────────────────────────────────────────
    op.create_table(
        "agent_templates",
        _uuid_pk(),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("purpose", sa.Text(), nullable=True),
        sa.Column("system_prompt", sa.Text(), nullable=True),
        # JSON blobs stored as JSONB for indexability on Postgres
        sa.Column("tool_policy_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("output_schema_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("approval_mode", sa.Text(), nullable=True),
        _ts("created_at", server_default_now=True),
        _ts("updated_at", server_default_now=True),
    )

    # ── agent_deployments ─────────────────────────────────────────────────────
    op.create_table(
        "agent_deployments",
        _uuid_pk(),
        _uuid_fk("agent_template_id", "agent_templates"),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column("scope_type", sa.Text(), nullable=True),
        sa.Column("scope_id", sa.Text(), nullable=True),
        sa.Column("status", sa.Text(), nullable=False, server_default="'draft'"),
        sa.Column("config_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        _ts("created_at", server_default_now=True),
        _ts("updated_at", server_default_now=True),
    )
    op.create_index("ix_agent_deployments_status", "agent_deployments", ["status"])

    # ── workflow_runs ─────────────────────────────────────────────────────────
    op.create_table(
        "workflow_runs",
        _uuid_pk(),
        sa.Column("workflow_type", sa.Text(), nullable=True),
        sa.Column("status", sa.Text(), nullable=True),
        sa.Column("input_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("output_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        _ts("started_at"),
        _ts("finished_at"),
        sa.Column("error_text", sa.Text(), nullable=True),
    )
    op.create_index("ix_workflow_runs_status", "workflow_runs", ["status"])
    op.create_index("ix_workflow_runs_workflow_type", "workflow_runs", ["workflow_type"])

    # ── google_sync_jobs ──────────────────────────────────────────────────────
    op.create_table(
        "google_sync_jobs",
        _uuid_pk(),
        sa.Column("job_type", sa.Text(), nullable=True),
        sa.Column("target_google_id", sa.Text(), nullable=True),
        sa.Column("status", sa.Text(), nullable=True),
        sa.Column("payload_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("result_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        _ts("created_at", server_default_now=True),
        _ts("updated_at", server_default_now=True),
    )
    op.create_index("ix_google_sync_jobs_status", "google_sync_jobs", ["status"])

    # ── evaluation_logs ───────────────────────────────────────────────────────
    op.create_table(
        "evaluation_logs",
        _uuid_pk(),
        sa.Column("event_type", sa.Text(), nullable=False),
        sa.Column("entity_type", sa.Text(), nullable=True),
        sa.Column("entity_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("payload_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("outcome", sa.Text(), nullable=True),
        sa.Column("metadata_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        _ts("created_at", nullable=False, server_default_now=True),
    )
    op.create_index("ix_evaluation_logs_event_type", "evaluation_logs", ["event_type"])
    op.create_index("ix_evaluation_logs_entity_type_entity_id", "evaluation_logs", ["entity_type", "entity_id"])
    op.create_index("ix_evaluation_logs_created_at", "evaluation_logs", ["created_at"])

    # ── updated_at auto-update triggers ──────────────────────────────────────
    # Create a reusable trigger function that sets updated_at = now() on every
    # UPDATE.  Attach it to every table that carries an updated_at column.
    op.execute("""
        CREATE OR REPLACE FUNCTION set_updated_at()
        RETURNS TRIGGER LANGUAGE plpgsql AS $$
        BEGIN
            NEW.updated_at = now();
            RETURN NEW;
        END;
        $$;
    """)

    for tbl in (
        "product_catalog",
        "bundles",
        "clients",
        "opportunities",
        "agent_templates",
        "agent_deployments",
        "google_sync_jobs",
    ):
        op.execute(f"""
            CREATE TRIGGER trg_{tbl}_updated_at
            BEFORE UPDATE ON {tbl}
            FOR EACH ROW EXECUTE FUNCTION set_updated_at();
        """)


# ---------------------------------------------------------------------------
# downgrade
# ---------------------------------------------------------------------------

def downgrade() -> None:
    # Drop triggers first
    for tbl in (
        "product_catalog",
        "bundles",
        "clients",
        "opportunities",
        "agent_templates",
        "agent_deployments",
        "google_sync_jobs",
    ):
        op.execute(f"DROP TRIGGER IF EXISTS trg_{tbl}_updated_at ON {tbl}")

    op.execute("DROP FUNCTION IF EXISTS set_updated_at()")

    # Drop tables in reverse dependency order
    op.drop_table("evaluation_logs")
    op.drop_table("google_sync_jobs")
    op.drop_table("workflow_runs")
    op.drop_table("agent_deployments")
    op.drop_table("agent_templates")
    op.drop_table("recommendations")
    op.drop_table("opportunities")
    op.drop_table("clients")
    op.drop_table("cross_sell_rules")
    op.drop_table("upsell_rules")
    op.drop_table("need_state_products")
    op.drop_table("need_states")
    op.drop_table("bundle_items")
    op.drop_table("bundles")
    op.drop_table("product_catalog")
